# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm run build-prod

      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha

      - save_cache:
          key: ng-nhjs-{{ checksum ".circle-sha" }}-{{ arch }}
          paths:
            - ~/repo/dist

  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha

      - restore_cache:
          keys:
            - ng-nhjs-{{ checksum ".circle-sha" }}-{{ arch }}

      - run:
          name: Deploy to S3
          command: aws s3 cp ~/repo/dist s3://ng-nhjs-repo/${CIRCLE_TAG}/ --recursive

workflows:
  version: 2
  ng-nhjs:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

